---
- hosts: server1
  remote_user: ubuntu
  become: true
  become_method: sudo
  serial: 2
  vars:
   install_dest: /home/ubuntu/mininet
  tasks:
   - name: Updating
     apt: update_cache=yes
   - name: Installing Git
     apt: name=git state=latest
   - name: Cloning mininet from Github  
     git: repo=git://github.com/mininet/mininet
          dest="{{install_dest}}"
          version=2.2.1
          accept_hostkey=yes
   - name: Installing mininet
     command: chdir="{{install_dest}}"
              util/install.sh -nfv
   - name: Checking mininet
     command: mn --test pingall