---
- hosts: server1
  remote_user: ubuntu
  become: true
  become_method: sudo
  tasks:
     - name: Installing Git
       apt: name=git state=latest
     - name: Cloning mininet from Github  
       git: repo=git://github.com/mininet/mininet
            dest=/root/mininet
            version=2.2.1
            accept_hostkey=yes
     - name: Moving to mininet directory
       shell: chdir /root/mininet
     - name: Installing mininet
       command: /root/mininet/util/install.sh